model_name: PET
model_key: pet
model_version: 1.1.0
date_added: "2025-05-28"
date_published: "2025-03-18"
authors:
  - name: Arslan Mazitov
    affiliation: COSMO, EPFL
    email: arslan.mazitov@epfl.ch
    corresponding: true
  - name: Filippo Bigi
    affiliation: COSMO, EPFL
    email: filippo.bigi@epf.ch
  - name: Matthias Kellner
    affiliation: COSMO, EPFL
    email: matthias.kellner@epfl.ch
  - name: Paolo Pegolo
    affiliation: COSMO, EPFL
    email: paolo.pegolo@epfl.ch
  - name: Davide Tisi
    affiliation: COSMO, EPFL
    email: davide.tisi.@epfl.ch
  - name: Guillaume Fraux
    affiliation: COSMO, EPFL
    email: guillaume.fraux@epf.ch
  - name: Sergey Pozdnyakov
    affiliation: COSMO, EPFL
    email: sergey.pozdnyakov@epfl.ch
  - name: Philip Loche
    affiliation: COSMO, EPFL
    email: philip.loche@epfl.ch
  - name: Michele Ceriotti
    affiliation: COSMO, EPFL
    email: michele.ceriotti@epfl.ch
    corresponding: true
repo: https://github.com/lab-cosmo/pet-mad
preprint: https://arxiv.org/abs/2503.14118
checkpoint_url: https://huggingface.co/lab-cosmo/pet-mad/resolve/b0234f3/models/pet-mad-latest.ckpt

openness: OSOD
train_task: S2EF
test_task: S2EF
targets: EF_G
model_type: Transformer
model_params: 4_000_000
trained_for_benchmark: false
n_estimators: 1

license:
  code: BSD-3-Clause
  code_url: https://github.com/lab-cosmo/pet-mad/blob/97b5ac301be3c5d7065af8f5cf40fc76b1825b6f/LICENSE

hyperparams:
  cutoff: 4.5
  cutoff_width: 0.2
  d_pet: 256
  d_head: 128
  d_feedforward: 512
  num_heads: 8
  num_attention_layers: 2
  num_gnn_layers: 2
  optimzer: Adam
  batch_size: 22
  learning_rate: 1e-4
  scheduler_patience: 250

training_cost:
  Nvidia H100 GPUs: {amount: 4, hours: 20}

requirements:
  metatrain: 2025.6
  huggingface_hub: 0.32.2
  platformdirs: 4.3.8

training_set: [MPtrj]

metrics:
  phonons:
    kappa_103:
      # pred_file: models/pet/kappa_results/conductivity.json.gz
      pred_file: models/pet/metrics.json.gz
      # pred_file: models/pet/metrics_with_script_like_esen.json.gz
      # pred_file_url: https://figshare.com/files/53461061
      κ_SRME: 1.1366
      κ_SRE: 1.017
  geo_opt:
    pred_file: models/pet/pet-wbm-IS2RE-FIRE.jsonl.gz
    struct_col: pet_structure
  discovery:
    pred_file: models/pet/pet.csv.gz
    # pred_file_url: https://figshare.com/files/54859376
    pred_col: e_form_per_atom_pet
    full_test_set:
      F1: .nan # fraction
      DAF: .nan # dimensionless
      Precision: .nan # fraction
      Recall: 0.0 # fraction
      Accuracy: 0.828 # fraction
      TPR: 0.0 # fraction
      FPR: 0.0 # fraction
      TNR: 1.0 # fraction
      FNR: 1.0 # fraction
      TP: 0.0 # count
      FP: 0.0 # count
      TN: 212871.0 # count
      FN: 44092.0 # count
      MAE: 3.916 # eV/atom
      RMSE: 3.996 # eV/atom
      R2: -502.014 # dimensionless
      missing_preds: 165916 # count
    unique_prototypes:
      F1: .nan # fraction
      DAF: .nan # dimensionless
      Precision: .nan # fraction
      Recall: 0.0 # fraction
      Accuracy: 0.845 # fraction
      TPR: 0.0 # fraction
      FPR: 0.0 # fraction
      TNR: 1.0 # fraction
      FNR: 1.0 # fraction
      TP: 0.0 # count
      FP: 0.0 # count
      TN: 182114.0 # count
      FN: 33374.0 # count
      MAE: 3.916 # eV/atom
      RMSE: 3.994 # eV/atom
      R2: -481.142 # dimensionless
      missing_preds: 138860 # count
    most_stable_10k:
      F1: .nan # fraction
      DAF: .nan # dimensionless
      Precision: .nan # fraction
      Recall: 0.0 # fraction
      Accuracy: 0.812 # fraction
      TPR: 0.0 # fraction
      FPR: 0.0 # fraction
      TNR: 1.0 # fraction
      FNR: 1.0 # fraction
      TP: 0.0 # count
      FP: 0.0 # count
      TN: 8123.0 # count
      FN: 1877.0 # count
      MAE: 2.462 # eV/atom
      RMSE: 2.512 # eV/atom
      R2: -191.146 # dimensionless
      missing_preds: 0 # count
