model_name: PET
model_key: pet
model_version: 1.1.0
date_added: "2025-05-28"
date_published: "2025-03-18"
authors:
  - name: Arslan Mazitov
    affiliation: COSMO, EPFL
    email: arslan.mazitov@epfl.ch
    corresponding: true
  - name: Filippo Bigi
    affiliation: COSMO, EPFL
    email: filippo.bigi@epf.ch
  - name: Matthias Kellner
    affiliation: COSMO, EPFL
    email: matthias.kellner@epfl.ch
  - name: Paolo Pegolo
    affiliation: COSMO, EPFL
    email: paolo.pegolo@epfl.ch
  - name: Davide Tisi
    affiliation: COSMO, EPFL
    email: davide.tisi.@epfl.ch
  - name: Guillaume Fraux
    affiliation: COSMO, EPFL
    email: guillaume.fraux@epf.ch
  - name: Sergey Pozdnyakov
    affiliation: COSMO, EPFL
    email: sergey.pozdnyakov@epfl.ch
  - name: Philip Loche
    affiliation: COSMO, EPFL
    email: philip.loche@epfl.ch
  - name: Michele Ceriotti
    affiliation: COSMO, EPFL
    email: michele.ceriotti@epfl.ch
    corresponding: true
repo: https://github.com/lab-cosmo/pet-mad
preprint: https://arxiv.org/abs/2503.14118
checkpoint_url: https://huggingface.co/lab-cosmo/pet-mad/resolve/b0234f3/models/pet-mad-latest.ckpt

openness: OSOD
train_task: S2EF
test_task: S2EF
targets: EF_G
model_type: Transformer
model_params: 4_000_000
trained_for_benchmark: false
n_estimators: 1

license:
  code: BSD-3-Clause
  code_url: https://github.com/lab-cosmo/pet-mad/blob/97b5ac301be3c5d7065af8f5cf40fc76b1825b6f/LICENSE

hyperparams:
  cutoff: 4.5
  cutoff_width: 0.2
  d_pet: 256
  d_head: 128
  d_feedforward: 512
  num_heads: 8
  num_attention_layers: 2
  num_gnn_layers: 2
  optimzer: Adam
  batch_size: 22
  learning_rate: 1e-4
  scheduler_patience: 250

training_cost:
  Nvidia H100 GPUs: {amount: 4, hours: 20}

requirements:
  metatrain: 2025.6
  huggingface_hub: 0.32.2
  platformdirs: 4.3.8

training_set: [MPtrj]

metrics:
  phonons:
    kappa_103:
      pred_file: models/pet/pet/2026-01-07-kappa-103-FIRE-dist=0.03-fmax=0.0001-symprec=1e-05/0_kappa.json.gz
      κ_SRME: 0.1794
      κ_SRE: 0.078
  geo_opt:
    pred_file: models/pet/pet-wbm-IS2RE-FIRE.jsonl.gz
    struct_col: pet_structure
    symprec=1e-2:
      rmsd: 0.067 # unitless
      n_sym_ops_mae: 2.6246 # unitless
      symmetry_decrease: 0.1648 # fraction
      symmetry_match: 0.7312 # fraction
      symmetry_increase: 0.0939 # fraction
      n_structures: 256963 # count
      analysis_file: models/pet/pet-wbm-IS2RE-FIRE-symprec=1e-2-moyo=0.4.4.csv.gz
      analysis_file_url:
  discovery:
    pred_file: models/pet/pet.csv.gz
    # pred_file_url: https://figshare.com/files/54859376
    pred_col: e_form_per_atom_pet
    full_test_set:
      F1: 0.903 # fraction
      DAF: 5.352 # dimensionless
      Precision: 0.918 # fraction
      Recall: 0.889 # fraction
      Accuracy: 0.967 # fraction
      TPR: 0.889 # fraction
      FPR: 0.016 # fraction
      TNR: 0.984 # fraction
      FNR: 0.111 # fraction
      TP: 39206.0 # count
      FP: 3489.0 # count
      TN: 209382.0 # count
      FN: 4886.0 # count
      MAE: 0.019 # eV/atom
      RMSE: 0.071 # eV/atom
      R2: 0.843 # dimensionless
      missing_preds: 2 # count
    unique_prototypes:
      F1: 0.923 # fraction
      DAF: 6.111 # dimensionless
      Precision: 0.934 # fraction
      Recall: 0.912 # fraction
      Accuracy: 0.976 # fraction
      TPR: 0.912 # fraction
      FPR: 0.012 # fraction
      TNR: 0.988 # fraction
      FNR: 0.088 # fraction
      TP: 30446.0 # count
      FP: 2143.0 # count
      TN: 179971.0 # count
      FN: 2928.0 # count
      MAE: 0.02 # eV/atom
      RMSE: 0.072 # eV/atom
      R2: 0.847 # dimensionless
      missing_preds: 0 # count
    most_stable_10k:
      F1: 0.986 # fraction
      DAF: 6.362 # dimensionless
      Precision: 0.973 # fraction
      Recall: 1.0 # fraction
      Accuracy: 0.973 # fraction
      TPR: 1.0 # fraction
      FPR: 1.0 # fraction
      TNR: 0.0 # fraction
      FNR: 0.0 # fraction
      TP: 9726.0 # count
      FP: 274.0 # count
      TN: 0.0 # count
      FN: 0.0 # count
      MAE: 0.015 # eV/atom
      RMSE: 0.065 # eV/atom
      R2: 0.907 # dimensionless
      missing_preds: 0 # count
